[package]
name = "faststats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "faststats"
crate-type = ["cdylib"]

[dependencies]
polars = { version = "0.40.0", features = ["performant", "random", "lazy"] }
pyo3 = "0.21.0"
pyo3-polars = "0.14.0"
rayon = "1.10.0"
